"""empty message

Revision ID: 05474cb9d35d
Revises: df4ab4e294df
Create Date: 2025-06-13 13:25:08.053940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05474cb9d35d'
down_revision = 'df4ab4e294df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
