"""empty message

Revision ID: 77e7a091ae95
Revises: 0506b39e3c10
Create Date: 2025-06-19 12:20:56.663461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e7a091ae95'
down_revision = '0506b39e3c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('asset_carteira_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'carteiras', ['carteira_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_carteira_id_fkey', 'asset', ['carteira_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
