"""alteração de lógica do banco de Assets

Revision ID: 8c097be14bd5
Revises: 77e7a091ae95
Create Date: 2025-06-21 16:11:57.501716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c097be14bd5'
down_revision = '77e7a091ae95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_constraint('asset_ticker_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_asset_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_ticker'), ['ticker'], unique=False)
        batch_op.create_unique_constraint('uq_carteira_ticker_date', ['carteira_id', 'ticker', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('uq_carteira_ticker_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_asset_ticker'))
        batch_op.drop_index(batch_op.f('ix_asset_date'))
        batch_op.create_unique_constraint('asset_ticker_key', ['ticker'])
        batch_op.alter_column('close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
